#!/bin/bash

# path to checkout of trunk
TRUNK_PATH=
# path to checkout of tags
TAG_PATH=

echo "This command will build LOCI Tools from the latest source,"
echo "copy it to the web site and tag the release in Subversion."
echo "Please be sure 'ant clean tools' works before proceeding."
echo -n "Are you sure you want to continue [y/n]? "
read reply
if echo "$reply" | grep -q "^[Yy]"
then
  echo -n
else
  exit
fi

echo
echo Checking out latest source...
cd $TRUNK_PATH
svn up

echo
echo Building jars...
ant clean tools

echo
echo Copying results to website...
cd artifacts
scp bio-formats.jar www.loci.wisc.edu:software
scp loci_tools.jar www.loci.wisc.edu:software

echo
echo Tagging release...
cd $TAG_PATH
svn up
DIR=`date +loci-tools-%Y-%b-%d`
mkdir -p $DIR/components
svn add $DIR

SVN_TRUNK="https://skyking.microscopy.wisc.edu/svn/java/trunk/"
SVN_TAG="https://skyking.microscopy.wisc.edu/svn/java/tags/$DIR"

# copy everything before committing

svn copy $SVN_TRUNK/build.properties $SVN_TAG
svn copy $SVN_TRUNK/build.xml $SVN_TAG
svn copy $SVN_TRUNK/checkstyle.xml $SVN_TAG
svn copy $SVN_TRUNK/common.properties $SVN_TAG
svn copy $SVN_TRUNK/common.xml $SVN_TAG
svn copy $SVN_TRUNK/global.properties $SVN_TAG
svn copy $SVN_TRUNK/jar $SVN_TAG
svn copy $SVN_TRUNK/components/bio-formats $SVN_TAG/components
svn copy $SVN_TRUNK/components/bio-formats-auto $SVN_TAG/components
svn copy $SVN_TRUNK/components/common $SVN_TAG/components
svn copy $SVN_TRUNK/components/loci-plugins $SVN_TAG/components
svn copy $SVN_TRUNK/components/forks $SVN_TAG/components
svn copy $SVN_TRUNK/components/ome-io $SVN_TAG/components
svn copy $SVN_TRUNK/components/ome-plugins $SVN_TAG/components
svn copy $SVN_TRUNK/components/ome-xml $SVN_TAG/components
svn copy $SVN_TRUNK/components/test-suite $SVN_TAG/components
svn copy $SVN_TRUNK/components/checkstyle $SVN_TAG/components

svn commit -m "`date +%Y\ %b\ %d\ release\ of\ LOCI\ Tools`"
svn up

echo
echo Results:
cd $TRUNK_PATH/artifacts/
ls -l bio-formats.jar loci_tools.jar
echo
echo Don\'t forget to update the web site:
echo web/ome/formats-download.html
echo web/software/index.html
