#!/bin/bash
cd ~/svn/java
for f in /Users/curtis/data/*
do
  if [ -d $f ] &&
    [ "${f:(-10)}" != "lost+found" ] &&
    [ "${f:(-11)}" != "screencasts" ] &&
    [ "${f:(-8)}" != "software" ] &&
    [ "${f:(-5)}" != "specs" ] &&
    [ "${f:(-4)}" != "test" ];
  then
    echo --------=========== Testing $f ===========--------
    ant -Dtestng.directory="$f" test-all
  fi
done
