#!/bin/bash
cd ~/svn/java
echo svn update:
svn up
echo ant dev-compile:
ant dev-compile
cd - > /dev/null
for f in data/*
do
  if [ -d "$f" ]
  then
    export dir=`echo $f | sed -e 's/data\///'`
    echo Processing $dir...
    export date=`date | sed -e 's/:/-/g'`
    java -mx512m loci.formats.test.ReaderTest $f -debug -time 2.3 \
      > "bio-formats-test-$date-$dir.out" 2> "bio-formats-test-$date-$dir.err"
  fi
done
cd - > /dev/null
