#!/bin/bash
DIR=/Users/curtis/data
echo --------=========== Sorting directories ===========--------
DIRS=`du -s /Users/curtis/data/* | sort -n | sed -e 's/^[0-9]*\s*//g'`
cd ~/svn/java
for f in $DIRS
do
  if [ -d $f ] &&
    [ "${f:(-10)}" != "lost+found" ] &&
    [ "${f:(-11)}" != "screencasts" ] &&
    [ "${f:(-8)}" != "software" ] &&
    [ "${f:(-5)}" != "specs" ] &&
    [ "${f:(-4)}" != "test" ];
  then
    echo --------=========== Testing $f ===========--------
    svn up
    ant -Dtestng.directory="$f" test-all
  fi
done
