#!/bin/bash

#
# branch-status - scan for branches with unpushed changes
#

repos=$(grep '^\[.*\]$' ~/.mrconfig |
	sed -e 's/^\[\(.*\)\]$/\1/')
for repo in $repos
do (
	test "$repo" != "DEFAULT" || continue
	cd "$HOME/$repo"
	test -d .git || continue
	repo="$(echo "$repo" | sed 's/.*\///')"

	# NB: Portions of the following were stolen from:
	# http://stackoverflow.com/a/2658301

	# check for dirty working copy
	test "$(git diff --shortstat 2> /dev/null | tail -n1)" == "" ||
		printf "%20s : %s\n" "$repo" "{DIRTY}"

	# check for stashes
	test "$(git stash list | tail -n1)" == "" ||
		printf "%20s : %s\n" "$repo" "{STASH}"

	# check for unpushed branches
	branches=$(git branch -vv |
		grep -v '\[[a-zA-Z0-9_\-\/]*\]' |
		sed -E 's/^\*? *//' |
		sed -E 's/  */~/g' )
	for branch in $branches
	do
		branch="$(echo "$branch" | sed 's/~/ /g')"
		test "$branch" == "" ||
			printf "%20s : %s\n" "$repo" "$branch"
	done
) done
