#!/bin/sh

# fix-git-remotes

# I like to clone Git repositories using the more performant git:// protocol.
# However, in typical use (e.g., as offered by GitHub and Bitbucket), this
# protocol operates read-only, since it does not support authentication.
#
# This script adjusts your local configuration so that remotes which fetch
# via git:// will use the read-write SSH protocol (git@...) when pushing.

for remote in $(git remote -v | grep '(push)$' | sed 's/^\([^	]*\)	\([^ ]*\).*/\1=\2/')
do
	case "$remote" in
		*=*)
			name=${remote%%=*}
			url=${remote#*=}
			pushURL=$(echo "$url" | sed 's_git://\([^/]*\)/_git@\1:_')
			cmd="remote set-url --push $name $pushURL"
			test "z$name" != "z" -a "$url" != "$pushURL" &&
				echo "git remote set-url --push \"$name\" \"$pushURL\"" &&
				git remote set-url --push "$name" "$pushURL"
			;;
		default)
			echo "[WARNING] Ignoring unparseable remote: $remote" 2>&1
			;;
	esac
done
