#!/bin/bash

# This script repairs HTML that has been clobbered by a WYSIWYG editor.

sed -E \
    -e 's_(<(blockquote|p|h[0-9]|ol|ul|table))_\
\
\1_g' \
    -e 's_(<(li|td|th|tr|/ol|/ul|/?tbody|/table))_\
\1_g'
