#!/bin/sh

#
# fixmod: a script for doing recursive chmod for files to 644 and dirs to 755
#

# TODO - Fix script to work for filenames with spaces.

find . -type d -exec chmod 755 {} \;
find . -type f -exec chmod 644 {} \;
