#!/bin/bash

# gen-mr - Lame script to generate .mrconfig entries for git repositories.

for f in $@
do
  (
  cd $f
  dir=$(pwd | sed -e "s/.*$USER\///")
  remote=$(git remote -v | grep origin | grep fetch | sed -e 's/^origin	//' -e 's/ (fetch)//')
  echo [$dir]
  echo "checkout = git clone $remote"
  echo
  )
done
