#!/bin/sh

# ipod-find: a script to search obfuscated iPod music for matching ID3v2 tags.

# Only searches MP3 format files. Requires the id3v2 command line tool.

IPOD_PATH="/Volumes/IPOD"

for f in $(find "$IPOD_PATH" -name '*.mp3')
do
  q="$(id3v2 -l "$f" | grep "$@")"
  if [ "$q" != "" ]
  then
    echo
    echo "$f"
    echo "$q"
  fi
done
