#!/bin/bash

#
# mbox2gmail: a script for auto-uploading mbox files to a Gmail account
#

#User Settings
MAILFILE="$1"
GMAILTO="ctrueden.wisc@gmail.com"

#Commands
DIR=`dirname "$0"`
python "$DIR/gml.py" mbox "${MAILFILE}" "${GMAILTO}"
#mkdir -p ~/gmailed/`dirname "${MAILFILE}"`
#mv "${MAILFILE}" ~/gmailed/`dirname "${MAILFILE}"`
