#!/bin/sh

# pom-versions: super hacky script to list pom-scijava version of all projects.

ls "$PATH_CODE"/*/*/pom.xml | \
	xargs grep -H pom-scijava -A 1 | \
	grep '<version>' | \
	sed -E 's/.*code\/(.*)\/pom.xml-.*<version>(.*)<\/version>/\2	\1/'
