#!/bin/bash

#
# upload-cfg: a script to clone console configuration to a remote server.
#

SERVER="$@"

if [ -z "$SERVER" ]
then
  echo "Please specify destination server."
  exit 1
fi

cd "$PRIVATE_DIR"
scp -r config "$SERVER:"
ssh "$SERVER" "bash config/config-links.sh"
