#!/bin/bash

# vcs-st - a helper script for checking the status of a working copy
#          works for CVS, Git, Mercurial and Subversion repositories

# Author: Curtis Rueden <ctrueden@wisc.edu>

dir="$1"
if [ "$dir" == "" ]
then
  dir="."
fi
if [ -d "$dir" ]
then
  cd "$dir"
else
  echo "=== Directory not found: '$dir' ==="
  exit -1
fi

# do a CVS status check (ugly!)
if [ -e CVS ]
then
  echo "=== Reporting status of CVS working copy in '$dir' ==="
  cvs status

# do a Git status check (vs. local repository only!)
elif [ -e .git ]
then
  echo "=== Reporting status of Git working copy in '$dir' ==="
  git status

# do a Mercurial status check (vs. local repository only!)
elif [ -e .hg ]
then
  echo "=== Reporting status of Mercurial working copy in '$dir' ==="
  hg status

# do an SVN status check (vs. local checkout only!)
elif [ -e .svn ]
then
  echo "=== Reporting status of Subversion working copy in '$dir' ==="
  svn status

else
  echo "=== No working copy found in '$dir' ==="
fi

if [ "$dir" != "" ]
then
  cd - > /dev/null
fi
