#!/bin/sh

# wi - "where is" - find a command or filename

cmd=$(which "$@")
if [ -z "$cmd" ]
then
  # no command found; see if git knows about it
  git_files="$(git ls-files "*$@")"
  if [ -z "$git_files" ]
  then
    # no file known to git; do a brute search
    files="$(find . -name "$@" | grep -v 'build/')"
    if [ ! -z "$files" ]
    then
      echo "$files"
    fi
  else
    echo "$git_files"
  fi
else
  echo "$cmd"
fi
