test "$DEBUG" && echo "[dotfiles] Loading plugin 'machines'..."

alias sha='ssh a'
alias shb='ssh b'
alias shc='ssh c'
alias shd='ssh d'
alias she='ssh e'
alias shf='ssh f'
alias shg='ssh g'
alias shh='ssh h'
alias shi='ssh i'
alias shj='ssh j'
alias shk='ssh k'
alias shl='ssh l'
alias shm='ssh m'
alias shn='ssh n'
alias sho='ssh o'
alias shp='ssh p'
alias shq='ssh q'
alias shr='ssh r'
alias shs='ssh s'
alias sht='ssh t'
alias shu='ssh u'
alias shv='ssh v'
alias shw='ssh w'
alias shx='ssh x'
alias shy='ssh y'
alias shz='ssh z'
