#alias sha='ssh abyssinian.loci.wisc.edu'
alias sha='ssh arrakis.microscopy.wisc.edu'
#alias shb='ssh balinese.loci.wisc.edu'
alias shb='ssh caladan.loci.wisc.edu'
#alias shc='ssh cheetoh.loci.wisc.edu'
alias shc='ssh dev.loci.wisc.edu'
#alias shd='ssh devonrex.loci.wisc.edu'
alias sho='ssh open.microscopy.wisc.edu'
