alias cyber='ssh cyber.microscopy.wisc.edu'
alias dev='ssh dev.loci.wisc.edu'
alias drupal='ssh drupal@skynet.loci.wisc.edu'
alias ome='ssh open.microscopy.wisc.edu'
alias server='ssh server.microscopy.wisc.edu'
alias skynet='ssh skynet.loci.wisc.edu'
alias tera='ssh tera.microscopy.wisc.edu'
