#!/bin/sh

#
# cp-redirects - Log ID mappings from forum.cellprofiler.org to forum.image.sc.
#

delays=(0 1 5 10 30 60 300)

download() {
  flags=$1
  url=$2
  outFile=$3
  for delay in $delays
  do
    test -s "$outFile" && break
    sleep $delay
    >&2 echo "curl $flags $url > $outFile"
    curl $flags "$url" > "$outFile"
  done
}

for cpID in $(seq 6446 1)
do
  cpRedirect="$cpID-cp-redirect"
  iscRedirect="$cpID-isc-redirect"
  cpContent="$cpID-cp-content"
  iscContent="$cpID-isc-content"

  # Discern slug from topic ID
  download -Is "http://forum.cellprofiler.org/t/$cpID" "$cpRedirect"
  slug=$(cat "$cpRedirect" | grep '^[Ll]ocation:' | cut -d' ' -f2 | cut -d'/' -f5)
  test "$slug" != "" || continue

  # Discern image.sc topic ID from slug
  download -Is "https://forum.image.sc/t/$slug" "$iscRedirect"
  iscID=$(cat "$iscRedirect" | grep '^[Ll]ocation:' | cut -d' ' -f2 | cut -d'/' -f6 | tr -d '\r')

  # Double check that it is really the same topic
  download -Ls "http://forum.cellprofiler.org/t/$cpID" "$cpContent"
  download -Ls "https://forum.image.sc/t/$iscID" "$iscContent"
  cpMeta=$(cat "$cpContent" | grep -A 4 '<meta property="og:title"')
  iscMeta=$(cat "$iscContent" | grep -A 4 '<meta property="og:title"')
  test "$cpMeta" = "$iscMeta" &&
    echo "$cpID -> $iscID" ||
    echo "$cpID -> $iscID [MISMATCH]"
done | tee mappings.txt
